apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - env:
        - name: HOWCHOO_HOST
          value: staging.howchoo.com
        - name: HOWCHOO_DB_HOST
          value: db
        - name: HOWCHOO_REDIS_HOST
          value: redis
        - name: HOWCHOO_DB_NAME
          value: postgres
        - name: HOWCHOO_ENV
          value: staging
        image: gcr.io/howchoo-161906/web:78c24ea373f19dc15c2da4abd15becf5add82282
        name: web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /secrets/database
          name: database
          readOnly: true
      volumes:
      - name: database
        secret:
          secretName: database
