apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - env:
        - name: HOWCHOO_HOST
          value: staging.howchoo.com
        - name: HOWCHOO_DB_HOST
          value: 127.0.0.1
        - name: HOWCHOO_REDIS_HOST
          value: redis
        - name: HOWCHOO_DB_NAME
          value: howchoo
        - name: HOWCHOO_ENV
          value: staging
        image: gcr.io/howchoo-161906/web:f6b156599915d6fb683bb67c731bf0f20cf04a47
        name: web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /secrets/database
          name: database
          readOnly: true
      - command:
        - /cloud_sql_proxy
        - -instances=<INSTANCE_CONNECTION_NAME>=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      volumes:
      - name: database
        secret:
          secretName: cloudsql-db-credentials
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
