apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      tier: backend
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
        - name: worker
          image: howchoo/web:kubernetes.03
          command: ["./howchoo/bin/start_celery.sh"]
          env:
            - name: HOWCHOO_HOST
              value: "howchoo.com"
            - name: HOWCHOO_DB_HOST
              value: "pg-master-101.cmn1bkeh6ucx.us-east-1.rds.amazonaws.com"
            - name: HOWCHOO_REDIS_HOST
              value: "redis"
            - name: HOWCHOO_DB_NAME
              value: "howchoo"
            - name: HOWCHOO_ENV
              value: "prod"
            - name: DEPLOY_VERSION
              value: "1"
          volumeMounts:
            - name: database
              mountPath: "/secrets/database"
              readOnly: true
      volumes:
        - name: database
          secret:
            secretName: database
