apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    tier: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:793451667086:certificate/bd95938d-5752-4eb4-a0b9-7a054692277a
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  loadBalancerIP:
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 80
  selector:
    app: web
    tier: frontend
